### ISSUE TITLE
Certfp not working -completed

### ISSUE THREAD

**Issue by TwinUsers** [adamh1989/FoxaIRCd#3]
Using both SSL and GNUTLS fails to display users finger print of certificate. This isn't good considering services offer nickserv/cert @adamh1989 You need to fix

**Comment by janicez** [comment]
"SSL" you mean Open SSL?

Also, the irca project needs suggestions... x.x

**Comment by adamh1989** [comment]
fix it then

Adam Hockley

**Comment by adamh1989** [comment]
@twinusers fix the bug then :D

**Comment by TwinUsers** [comment]
Not my issue really. Something you've got to maintain being as foxaircd is a project of foxatomic.net

**Comment by adamh1989** [comment]
now fixed
